TestNet/ViewModels/CustomerViewModel.cs
using TestNet.SqlDataAccess.Entities;

namespace TestNet.ViewModels
{
    public class CustomerViewModel : Customer
    {
    }
}

TestNet/ViewModels/MVCGridToolbarModel.cs
namespace TestNet.ViewModels
{
    public class MVCGridToolbarModel
    {
        public MVCGridToolbarModel()
        {

        }

        public MVCGridToolbarModel(string gridName)
        {
            MVCGridName = gridName;
        }

        public string MVCGridName { get; set; }
        public bool PageSize { get; set; }
        public bool ColumnVisibility { get; set; }
        public bool Export { get; set; }
        public bool GlobalSearch { get; set; }
    }
}

TestNet/Controllers/BaseController.cs
using System.Web.Mvc;

namespace TestNet.Controllers
{
    public class BaseController : Controller
    {
        protected override void OnException(ExceptionContext filterContext)
        {
            string controllerName = (string)filterContext.RouteData.Values["controller"];
            string actionName = (string)filterContext.RouteData.Values["action"];

            var model = new HandleErrorInfo(filterContext.Exception, controllerName, actionName);

            ViewResult view = new ViewResult
            {
                ViewName = "Error",
                ViewData = new ViewDataDictionary<HandleErrorInfo>(model)
            };
            
            filterContext.Result = view;
            filterContext.ExceptionHandled = true;
        }
    }
}

TestNet/Controllers/CustomerController.cs
using System.Web.Mvc;
using TestNet.Domain.Contract.Services;
using TestNet.SqlDataAccess.Entities;
using TestNet.ViewModels;

namespace TestNet.Controllers
{
    public class CustomerController : BaseController
    {
        private readonly ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            Customer customer = null;

            if (id.HasValue)
            {
                customer = _customerService.GetById(id.Value);
            }
            else
            {
                customer = new Customer();
            }

            CustomerViewModel model = new CustomerViewModel()
            {
                Id = customer.Id,
                FirstName = customer.FirstName,
                LastName = customer.LastName,
                City = customer.City,
                Country = customer.Country,
                Phone = customer.Phone
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            Customer customer = null;

            customer = _customerService.GetById(id);

            CustomerViewModel model = new CustomerViewModel()
            {
                Id = customer.Id,
                FirstName = customer.FirstName,
                LastName = customer.LastName,
                City = customer.City,
                Country = customer.Country,
                Phone = customer.Phone
            };

            return View(model);
        }

        [HttpPost]
        [HandleError()]
        public ActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                _customerService.Save(customer);

                return Redirect("/customer");
            }
            else
            {
                return View(customer);
            }
        }

        [HttpPost]
        public ActionResult Delete(Customer customer)
        {
            _customerService.Delete(customer);

            return Redirect("/customer");
        }
    }
}

TestNet/Controllers/HomeController.cs
using System.Web.Mvc;

namespace TestNet.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return Redirect("/customer");
        }
    }
}

TestNet/Views/Customer/Delete.cshtml
@model TestNet.ViewModels.CustomerViewModel

@{
    ViewBag.Title = "Delete Customer";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Delete Customer</h4>
    <hr />
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Do you like remove the customer</label>
                @Html.LabelForModel(Model.FirstName, new { htmlAttributes = new { @class = "control-label" } })
                @Html.LabelForModel(Model.LastName, new { htmlAttributes = new { @class = "control-label" } })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Delete" class="btn btn-primary" />
            <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "Customer") + "'");" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestNet/Views/Customer/Edit.cshtml
@model TestNet.ViewModels.CustomerViewModel

@{
    ViewBag.Title = "Edit Customer";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <label class="control-label col-md-2">First Name</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Last Name</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">City</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Country</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Phone</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "Customer") + "'");" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestNet/Views/Customer/Index.cshtml
@{
    ViewBag.Title = "Customer";
}

<h4 class="title">Customer</h4>
<div class="well">
    <div class="form-inline">
        <input type="button" class="btn btn-primary" value="Create Customer" onclick="location.href='@Url.Action("Edit", "Customer")'" />
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        @Html.Partial("_MVCGridToolbar", new TestNet.ViewModels.MVCGridToolbarModel()
        {
            MVCGridName = "Customers",
            PageSize = true,
            ColumnVisibility = false,
            Export = false,
            GlobalSearch = true
        })
        @Html.MVCGrid("Customers")
    </div>
</div>

TestNet/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TestNet/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TestNet/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TestNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Test MVC Casarella Fabian", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Customer", "Index", "Customer")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Fabian Casarella Test MVC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/MVCGridHandler.axd/script.js"></script>
</body>
</html>

TestNet/Views/Shared/_MVCGridToolbar.cshtml
@model TestNet.ViewModels.MVCGridToolbarModel
@{
    string gridName = Model.MVCGridName;
}

<div class="row">
    <div class="col-md-3">
        <div class="form-inline">
            @if (Model.PageSize)
            {
                <div class="form-group">
                    <label>
                        Page Size: <select class="form-control" data-mvcgrid-type="pageSize" data-mvcgrid-name="@(gridName)">
                            <option value="10">10</option>
                            <option value="25">25</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                        </select>
                    </label>
                </div>
            }
        </div>
    </div>
    <div class="col-md-9">
        <div class="form-inline pull-right">
            <div class="btn-group">
                @if (Model.ColumnVisibility)
                {
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            <span class="glyphicon glyphicon-list" aria-hidden="true"></span> Fields
                        </button>
                        <ul class="dropdown-menu" role="menu" data-mvcgrid-type="columnVisibilityList" data-mvcgrid-name="@(gridName)"></ul>
                    </div>
                }
                @if (Model.Export)
                {
                    <button class="btn btn-default" data-mvcgrid-type="export" data-mvcgrid-name="@(gridName)">
                        <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span> Export
                    </button>
                }
            </div>

            @if (Model.GlobalSearch)
            {
                <span>&nbsp;</span>
                <div class="form-group">
                    <label>
                        Search: <input type="search" placeholder="Search" class="form-control"
                                       data-mvcgrid-type="additionalQueryOption" data-mvcgrid-option="search" data-mvcgrid-name="@(gridName)"
                                       data-mvcgrid-apply-additional="keyup">
                    </label>
                </div>
            }
        </div>
    </div>
</div>